
name: Print Author Association

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Print Author Association
        shell: bash
        env:
         JSON: ${{ toJSON(github) }}
        run: |
            echo ${{ github.event.pull_request.author_association }}
            echo $JSON
